<a href="https://colab.research.google.com/github/maheshgenai22/Python-code-for-scrape-product-details-/blob/main/aiml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
df=pd.read_csv('/content/EDA_data.csv')
df.head()

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0        0.0
1  15810944    Male  35.0          20000.0        0.0
2  15668575  Female  26.0          43000.0        0.0
3  15603246  Female  27.0          57000.0        0.0
4  15804002    Male  19.0          76000.0        0.0

In [ ]:
df=pd.read_csv('/content/EDA_data.csv')
df.head(20)

     User ID  Gender   Age  EstimatedSalary  Purchased
0   15624510    Male  19.0          19000.0        0.0
1   15810944    Male  35.0          20000.0        0.0
2   15668575  Female  26.0          43000.0        0.0
3   15603246  Female  27.0          57000.0        0.0
4   15804002    Male  19.0          76000.0        0.0
5   15728773    Male  27.0          58000.0        0.0
6   15598044  Female  27.0          84000.0        0.0
7   15694829  Female  32.0         150000.0        1.0
8   15600575     NaN  25.0          33000.0        0.0
9   15727311     NaN  35.0          65000.0        0.0
10  15570769     NaN  26.0          80000.0        0.0
11  15606274     NaN  26.0          52000.0        0.0
12  15746139     NaN  20.0              NaN        0.0
13  15704987     NaN  32.0              NaN        0.0
14  15628972     NaN  18.0              NaN        NaN
15  15697686     NaN  29.0              NaN        NaN
16  15733883     NaN  47.0              NaN        NaN
17  15617482     NaN  45.0              NaN        NaN
18  15704583     NaN  46.0              NaN        NaN
19  15621083     NaN  48.0              NaN        NaN

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print("a is greater than b")
elif b > a:
    print("b is greater than a")
else:
    print("Both numbers are equal")

Enter first number: 31
Enter second number: 22
a is greater than b

In [ ]:
i=1

while i <=10:
print(4*i)
i+=1

SyntaxError: expected ':' (2221727746.py, line 3)