<a href="https://colab.research.google.com/github/maheshgenai22/Python-code-for-scrape-product-details-/blob/main/Day3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/Feature_Scaling.csv')
df.head()

   Country  Age  Salary  Purchased
0   France   44   72000          0
1    Spain   27   48000          1
2  Germany   30   54000          0
3    Spain   38   61000          0
4  Germany   40    1000          1

In [ ]:
df.shape

(10, 4)

In [ ]:
df.describe()

             Age        Salary  Purchased
count  10.000000     10.000000  10.000000
mean   42.700000  57500.000000   0.500000
std    14.368561  22974.623682   0.527046
min    27.000000   1000.000000   0.000000
25%    35.500000  52500.000000   0.000000
50%    39.000000  59500.000000   0.500000
75%    47.000000  70750.000000   1.000000
max    78.000000  83000.000000   1.000000

In [ ]:
df2=df[['Age','Salary']]
df2.head(2)

   Age  Salary
0   44   72000
1   27   48000

In [ ]:
#Now first check any missing values present

df2.isnull().sum()

Age       0
Salary    0
dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [ ]:
sc=StandardScaler()
sc.fit(df2)

StandardScaler()

In [ ]:
sc.mean_

array([4.27e+01, 5.75e+04])

In [ ]:
sc.scale_

array([1.36312142e+01, 2.17956418e+04])

In [ ]:
df2.describe()

             Age        Salary
count  10.000000     10.000000
mean   42.700000  57500.000000
std    14.368561  22974.623682
min    27.000000   1000.000000
25%    35.500000  52500.000000
50%    39.000000  59500.000000
75%    47.000000  70750.000000
max    78.000000  83000.000000

In [ ]:
df2_sc = pd.DataFrame(df2, columns=['Age', 'Salary'])

In [ ]:
df2_sc.describe().round(2)

         Age    Salary
count  10.00     10.00
mean   42.70  57500.00
std    14.37  22974.62
min    27.00   1000.00
25%    35.50  52500.00
50%    39.00  59500.00
75%    47.00  70750.00
max    78.00  83000.00

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

mmc = MinMaxScaler()

df2_mmc = mmc.fit_transform(df2[['Age', 'Salary']])

df2_mmc = pd.DataFrame(df2_mmc, columns=['Age', 'Salary'])

df2_mmc

        Age    Salary
0  0.333333  0.865854
1  0.000000  0.573171
2  0.058824  0.646341
3  0.215686  0.731707
4  0.254902  0.000000
5  0.156863  0.695122
6  1.000000  0.621951
7  0.411765  0.951220
8  0.450980  1.000000
9  0.196078  0.804878

In [ ]:
df2_mmc=pd.DataFrame(df2_mmc,columns=['Age','Salary'])
df2_mmc

        Age    Salary
0  0.333333  0.865854
1  0.000000  0.573171
2  0.058824  0.646341
3  0.215686  0.731707
4  0.254902  0.000000
5  0.156863  0.695122
6  1.000000  0.621951
7  0.411765  0.951220
8  0.450980  1.000000
9  0.196078  0.804878